// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListUserFiles(arg1:string,arg2:string):Promise<Array<main.FileItem>>;

export function LoginUser(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UploadFile(arg1:string,arg2:string,arg3:Array<number>,arg4:string):Promise<void>;
