// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSetupStatus() {
  return window['go']['main']['App']['CheckSetupStatus']();
}

export function CreateDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2, arg3);
}

export function DebugFileLocations() {
  return window['go']['main']['App']['DebugFileLocations']();
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function GetDebugSetupInfo() {
  return window['go']['main']['App']['GetDebugSetupInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListUserFiles(arg1, arg2) {
  return window['go']['main']['App']['ListUserFiles'](arg1, arg2);
}

export function LoginUser(arg1, arg2) {
  return window['go']['main']['App']['LoginUser'](arg1, arg2);
}

export function PerformSetup(arg1, arg2, arg3) {
  return window['go']['main']['App']['PerformSetup'](arg1, arg2, arg3);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}
